name: Node.js CI
on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: corepack enable yarn

      - name: Install development dependencies
        run: yarn install

      - name: Build & Code analysis
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            lib/**/*.js
            lib/**/*.js.map
            lib/**/*.d.ts
            test/**/*.js
            test/**/*.js.map

  test:

    runs-on: ubuntu-latest

    needs: build

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable yarn

      - name: Install dependencies
        run: yarn install

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test

